global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'spring-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - order-service:8081
          - inventory-service:8082
          - notification-service:8083

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
